# GH Pages Config
lsi: false
safe: true
title: GetDat - Python Package
show_downloads: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: GFM
remote_theme: pages-themes/hacker@v0.2.0 # https://github.com/pages-themes/hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
