name: Tests Suite
description: 'Runs test suite associated with python package'
on:
  push:
    branches:
      - master
  pull_request:
  # manually trigger workflow
  workflow_dispatch:

jobs:
  run_test_suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pipx & Poetry
        run: python3 -m pip install --user pipx
        run: python3 -m pipx ensurepath
        run: pipx install poetry
      
      - name: Install Dependencies & Test Dependencies
        run: poetry install --with test

      - name: Run Pytest
        run: pytest -v

